package com.lynx.auth_service.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@Entity
@Getter
@Setter
@Table(name = "users")
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Primary key, auto-generated by the database (auto-increment)

    @Column(unique = true)
    private String email;

    private String password;

    @Column(unique = true)
    private String username;

    private String firstName;
    private String lastName;
    private LocalDate dateOfBirth;
}