services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: lynx_auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      COOKIE_SECURE: ${COOKIE_SECURE}

    ports:
      - "5434:5432"
